services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ipc: host
    shm_size: '2gb'
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DB_PATH=${DB_PATH}
      - FRONTEND_URL=${FRONTEND_URL}
      - BOT_NAME=${BOT_NAME}
      - GOOGLE_ACCOUNT_EMAIL=${GOOGLE_ACCOUNT_EMAIL}
      - GOOGLE_ACCOUNT_PASSWORD=${GOOGLE_ACCOUNT_PASSWORD}
      - AUTH_STATE_PATH=${AUTH_STATE_PATH}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME}
      - REGISTRATION_ENABLED=${REGISTRATION_ENABLED}
      - STORAGE_PATH=${STORAGE_PATH:-.data/recordings}
    volumes:
      - backend-data:/app/data
      - backend-recordings:/app/.data/recordings

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - RUNTIME_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend


volumes:
  backend-data:
  backend-recordings:
